# Generated by Django 2.1 on 2020-01-14 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_offers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Offers',
            new_name='Offer',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='discounts',
            new_name='discount',
        ),
    ]
